/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("comugamers.common-conventions")
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

dependencies {
    implementation("org.javassist:javassist:3.29.2-GA")
    implementation("org.yaml:snakeyaml:1.26")
    compileOnly("org.spigotmc:spigot-api:1.14.4-R0.1-SNAPSHOT")
    compileOnly("com.mojang:datafixerupper:1.0.20")
}

tasks {
    jar {
        manifest {
            attributes["Premain-Class"] = "com.grinderwolf.swm.clsm.NMSTransformer"
        }
    }

    shadowJar {
        archiveClassifier.set("")
    }

    assemble {
        dependsOn(shadowJar)
    }
}

dependencies {
    implementation("org.javassist:javassist:3.25.0-GA")
    implementation("org.yaml:snakeyaml:1.26")
    compileOnly("com.mojang:datafixerupper:1.0.20")
    compileOnly("org.spigotmc:spigot-api:1.14.4-R0.1-SNAPSHOT")
}
repositories {
    mavenCentral()
}
